/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import locale from 'element-ui/src/locale';

const components = [
  Button
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.15.14',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Button
};
